jabberd2: _sx_plugin_st Struct Reference
_sx_plugin_st Struct Reference
a plugin
#include <sx.h>
Data Fields
sx_env_t env
int magic
int index
void * private
void(* new)(sx_t s, sx_plugin_t p)
void(* free)(sx_t s, sx_plugin_t p)
void(* client)(sx_t s, sx_plugin_t p)
void(* server)(sx_t s, sx_plugin_t p)
int(* wio)(sx_t s, sx_plugin_t p, sx_buf_t buf)
int(* rio)(sx_t s, sx_plugin_t p, sx_buf_t buf)
int(* wnad)(sx_t s, sx_plugin_t p, nad_t nad, int elem)
int(* rnad)(sx_t s, sx_plugin_t p, nad_t nad)
void(* header)(sx_t s, sx_plugin_t p, sx_buf_t buf)
void(* stream)(sx_t s, sx_plugin_t p)
void(* features)(sx_t s, sx_plugin_t p, nad_t nad)
int(* process)(sx_t s, sx_plugin_t p, nad_t nad)
void(* unload)(sx_plugin_t p)
Detailed Description
a plugin
Definition at line 347 of file sx.h.
Field Documentation
sx_env_t _sx_plugin_st::env
Definition at line 348 of file sx.h.
Referenced by sx_env_plugin().
int _sx_plugin_st::magic
Definition at line 350 of file sx.h.
Referenced by sx_ssl_init().
int _sx_plugin_st::index
Definition at line 352 of file sx.h.
Referenced by _sx_ack_features(), _sx_ack_process(), _sx_compress_free(), _sx_compress_new(), _sx_compress_rio(), _sx_compress_wio(), _sx_sasl_client_process(), _sx_sasl_features(), _sx_sasl_free(), _sx_sasl_process(), _sx_sasl_rio(), _sx_sasl_stream(), _sx_sasl_wio(), _sx_ssl_client(), _sx_ssl_free(), _sx_ssl_process(), _sx_ssl_rio(), _sx_ssl_server(), _sx_ssl_wio(), _sx_websocket_free(), _sx_websocket_new(), _sx_websocket_rio(), _sx_websocket_wio(), sx_env_plugin(), sx_sasl_auth(), and sx_ssl_client_starttls().
void* _sx_plugin_st::private
Definition at line 354 of file sx.h.
Referenced by _bind_features(), _sx_sasl_client_process(), _sx_sasl_features(), _sx_sasl_unload(), _sx_ssl_client(), _sx_ssl_server(), _sx_ssl_unload(), _sx_websocket_rio(), bind_init(), sx_sasl_auth(), sx_sasl_init(), sx_ssl_init(), sx_ssl_server_addcert(), and sx_websocket_init().
void(* _sx_plugin_st::new) (sx_t s, sx_plugin_t p)
Definition at line 356 of file sx.h.
Referenced by sx_new().
void(* _sx_plugin_st::free) (sx_t s, sx_plugin_t p)
Definition at line 357 of file sx.h.
Referenced by sx_compress_init(), sx_free(), sx_sasl_init(), sx_ssl_init(), and sx_websocket_init().
void(* _sx_plugin_st::client) (sx_t s, sx_plugin_t p)
Definition at line 359 of file sx.h.
Referenced by sx_client_init(), sx_compress_init(), and sx_ssl_init().
void(* _sx_plugin_st::server) (sx_t s, sx_plugin_t p)
Definition at line 360 of file sx.h.
Referenced by sx_compress_init(), sx_server_init(), sx_ssl_init(), and sx_websocket_init().
int(* _sx_plugin_st::wio) (sx_t s, sx_plugin_t p, sx_buf_t buf)
Definition at line 363 of file sx.h.
Referenced by _sx_chain_io_write(), sx_compress_init(), sx_sasl_init(), sx_ssl_init(), and sx_websocket_init().
int(* _sx_plugin_st::rio) (sx_t s, sx_plugin_t p, sx_buf_t buf)
Definition at line 364 of file sx.h.
Referenced by _sx_chain_io_read(), sx_compress_init(), sx_sasl_init(), sx_ssl_init(), and sx_websocket_init().
int(* _sx_plugin_st::wnad) (sx_t s, sx_plugin_t p, nad_t nad, int elem)
Definition at line 367 of file sx.h.
Referenced by _sx_chain_nad_write().
int(* _sx_plugin_st::rnad) (sx_t s, sx_plugin_t p, nad_t nad)
Definition at line 368 of file sx.h.
Referenced by _sx_chain_nad_read().
void(* _sx_plugin_st::header) (sx_t s, sx_plugin_t p, sx_buf_t buf)
Definition at line 370 of file sx.h.
Referenced by _sx_server_element_start(), s2s_db_init(), sx_ack_init(), and sx_client_init().
void(* _sx_plugin_st::stream) (sx_t s, sx_plugin_t p)
Definition at line 371 of file sx.h.
Referenced by _sx_client_element_start(), _sx_server_notify_header(), and sx_sasl_init().
void(* _sx_plugin_st::features) (sx_t s, sx_plugin_t p, nad_t nad)
Definition at line 373 of file sx.h.
Referenced by _sx_server_notify_header(), address_init(), bind_init(), s2s_db_init(), sx_ack_init(), sx_compress_init(), sx_sasl_init(), and sx_ssl_init().
int(* _sx_plugin_st::process) (sx_t s, sx_plugin_t p, nad_t nad)
Definition at line 376 of file sx.h.
Referenced by _sx_process_read(), sx_ack_init(), sx_compress_init(), sx_sasl_init(), and sx_ssl_init().
void(* _sx_plugin_st::unload) (sx_plugin_t p)
Definition at line 378 of file sx.h.
Referenced by sx_env_free(), sx_sasl_init(), and sx_ssl_init().
The documentation for this struct was generated from the following file:
sx/sx.h